### ISSUE TITLE
Metrics - Problem with Zipkin Kafka Sender

### ISSUE THREAD

**Issue by bob04619** [yidongnan/grpc-spring-boot-starter#167]
Hi, I have a test project for collecting metrics with Zipkin, but I'm receiving an error when using your framework with a Zipkin sender over Kafka.

```
Parameter 2 of method reporter in org.springframework.cloud.sleuth.zipkin2.ZipkinAutoConfiguration required a bean of type 'zipkin2.reporter.Sender' that could not be found.
	- Bean method 'kafkaSender' not loaded because @ConditionalOnBean (types: org.springframework.boot.autoconfigure.kafka.KafkaProperties; SearchStrategy: all) did not find any beans of type org.springframework.boot.autoconfigure.kafka.KafkaProperties
	- Bean method 'rabbitSender' not loaded because ZipkinSender org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRabbitSenderConfiguration kafka sender type
	- Bean method 'restTemplateSender' not loaded because ZipkinSender org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration kafka sender type
```

However these scenarios work fine - I created multiple working branches for each scenario:

1. No grpc framework, with Zipkin sender:
https://github.com/bob04619/sleuth-grpc-framework-testing/tree/master

2. No grpc framework, with Zipkin sender over Kafka:
https://github.com/bob04619/sleuth-grpc-framework-testing/tree/kafka

3. With grpc framework, and the Zipkin sender:
https://github.com/bob04619/sleuth-grpc-framework-testing/tree/with-grpc-framework

Problem branch:
https://github.com/bob04619/sleuth-grpc-framework-testing/tree/kafka-with-grpc-framework

As soon as I configure zipkin to send over kafka it errors. Only changes are yaml config:

```
spring:
  zipkin:
    sender:
      type: kafka
```

And additional dependency, as described in Spring Boot docs:

`implementation 'org.springframework.kafka:spring-kafka'`

**Comment by ST-DDT** [comment]
The given example project uses Java 8 and Gradle 4.10

I don't have a running kafka setup atm and thus its hard to test this case.

I was able to start the application without a local kafka instance by skipping the tests:

* `./gradlew clean bootRun -x test`

----------------------------

I assume this is an ordering issue with one of the configurations.
The grpc tracing part requires loading the sleuth part, which thefore might start before the kafka config is initialized. If you manually trigger the kafka config initialization by adding the following snippet to your configuration classes:

````java
@EnableConfigurationProperties(KafkaProperties.class)
````

Then the application will start. However, I cannot guarantee that the application actually works with that setup without a running kafka instance.

Can you also open an issue in spring-cloud-sleuth(?) and report that issue there?
IMO spring-boot-sleuth is responsible for making sure that their setup runs after kafka's, but that's only a guess.

**Comment by bob04619** [comment]
Great, thanks, that annotation worked and it seems to be writing to zipkin in the same way as without kafka sender. Do you think any other unforeseen issues could arise related to this?

Also if you ever need it, I'm just running a dockerized setup of zipkin/zookeeper/kafa based on this guide:
[https://www.e4developer.com/2018/05/20/how-to-easily-run-kafka-with-docker-for-development](https://www.e4developer.com/2018/05/20/how-to-easily-run-kafka-with-docker-for-development)

The code originally worked almost verbatim on the lognet framework, but it must be a different setup under the covers as with his framework you need a Global Interceptor and manually inject the brave.grpc.GrpcTracing.newServerInterceptor(). Which lead me to believe you guys may be doing something different initializing sleuth.

I will try to dig into Sleuth docs about initialization ordering before posting there.

**Comment by ST-DDT** [comment]
> Great, thanks, that annotation worked and it seems to be writing to zipkin in the same way as without kafka sender. Do you think any other unforeseen issues could arise related to this?

No, AFAICT there *shouldn't* be any issues.

> The code originally worked almost verbatim on the lognet framework, but it must be a different setup under the covers as with his framework you need a Global Interceptor and manually inject the brave.grpc.GrpcTracing.newServerInterceptor(). Which lead me to believe you guys may be doing something different initializing Sleuth.

Well, without being sure, i would say the aren't any big differences between those two cases.
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/autoconfigure/GrpcCommonTraceAutoConfiguration.java#L30-L39
and
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerAutoConfiguration.java#L147-L159

AFAICT there are two differences though.

1. For lognet you configure it in your own configuration, which is always loaded (read) first. We provide it as an optional/automatic feature
2. We use `@AutoConfigureBefore` / `@AutoConfigureAfter` whereas the lognet library just uses `@AutoConfigureOrder`

If you manually configure the grpc tracing, then the (tracing) server bean interceptor definition will be registered in your context - which is loaded first - and registered in the application context. We provide it as an out of the box feature, thus we have to use `@Conditional`s. To prevent any issues, we explicitly state, that our setup needs to run after the tracing setup. I assume it would also work if we use the auto order but I feel reluctant to trust it for optional stuff; especially after this issue. I'm not sure how spring determines the load order, but I assume that you can reproduce the same error with the other lib, if you change the order of the dependencies or names of the jar files.

Unfortunately, I don't know the exact mechanisms here, maybe we do it wrong, maybe we are just unlucky with the dependency order or file name. That's the main reason why I suggested opening the issue upstream. I hope there are people who know more about the internals and I assume that their library is probably the best suited to permanently fix this kind of error (instead of using the current workaround).

**Comment by ST-DDT** [comment]
I opened an issue in spring-cloud-sleuth to discus that issue some more: 
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1209

**Comment by ST-DDT** [comment]
Fixed upstream
