### ISSUE TITLE
Exposing the starter as a transitive dependnecy

### ISSUE THREAD

**Issue by pluttrell** [yidongnan/grpc-spring-boot-starter#193]
We're using Gradle 5.2.1 and have switched most dependency configurations from `compile` to `implementation`. When I do that we this dependency, it's not exposed as a transitive dependency to other modules in the same project. Wondering if it should work?

**Comment by ST-DDT** [comment]
Sorry, I'm not sure what you refer to.
AFAICT we declare spring-boot-starter as transitive dependency.

**Comment by ST-DDT** [comment]
According to https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html

> **implementation**
> 
> The dependencies required to compile the production source of the project which are not part of the API exposed by the project. For example the project uses Hibernate for its internal persistence layer implementation.

And according to the example on https://docs.gradle.org/current/userguide/dependency_types.html#dependency_types

You might want to try the `runtime` scope. However I'm not a gradle expert.
If I want to use the GrpcXXXConfigurers I would go for `compile` otherwise for `runtime`.

**Comment by ST-DDT** [comment]
Closing due to missing feedback. If the question is still relevant, we can reopen it.
