### ISSUE TITLE
How to setup a global error handler interceptor

### ISSUE THREAD

**Issue by wangzw** [yidongnan/grpc-spring-boot-starter#226]
What is the design purpose of calling service specific interceptor before global interceptor?

My use case is that, I want to setup a global interceptor to handle all exceptions from service implementation and other interceptors. But I got interceptor order issues. First I cannot guarantee the global interceptor order, I guess #215 can fix this issue. But I found another issue with service specific interceptor, it seems called before global interceptor.

```
public @interface GrpcService {

    /**
     * A list of {@link ServerInterceptor} classes that should be applied to only this service. If a bean of the given
     * type exists, it will be used; otherwise a new instance of that class will be created via no-args constructor.
     *
     * <p>
     * <b>Note:</b> These interceptors will be applied after the global interceptors. But the interceptors that were
     * applied last, will be called first.
     * </p>
     *
     * @return A list of ServerInterceptor classes that should be used.
     */
    Class<? extends ServerInterceptor>[] interceptors() default {};

    /**
     * A list of {@link ServerInterceptor} beans that should be applied to only this service.
     *
     * <p>
     * <b>Note:</b> These interceptors will be applied after the global interceptors and the interceptor classes. But
     * the interceptors that were applied last, will be called first.
     * </p>
     *
     * @return A list of ServerInterceptor beans that should be used.
     */
    String[] interceptorNames() default {};

}

```

Is there any way to setup a global interceptor that called as the first interceptor and handle all exceptions from service implementation or other interceptor?

I currently rewrite `AnnotationGrpcServiceDiscoverer` to manually adjust the order of interceptors to move my global error handler interceptor to the end of the list and get first called. It works but looks like a hack way.

**Comment by ST-DDT** [comment]
> What is the design purpose of calling service specific interceptor before global interceptor?

Historical reasons. Previously grpc only provided a method that applied the interceptors in reverse order. Without the actual ability to sort interceptors, we somewhat considered the global and user defined mutually exclusive. 
We haven't changed this logic since to remain backwards compatible.

Maybe with the new sort feature we could change our logic here as well.
@yidongnan What do you think?
@wangzw Which design would you consider best?

Things to consider:
* Global and custom interceptors explicitly exclusive
* User defined order for custom interceptors or priority based.
  * can user defined interceptors run between two global ones?
* custom interceptors before or after global ones
* how should interceptor groups be ordered
  * metric and tracing
  * security
  * exception mapping
  * which other groups are there?

> Is there any way to setup a global interceptor that called as the first interceptor and handle all exceptions from service implementation or other interceptor?

Currently there is nothing build-in for that.
You can can use spring mechanics to order certain configuration classes though.

Overwriting that class is probably the simpliest solution right now.

Have you tried using a `GlobalServerInterceptorConfigurer` and manipulating the registry via its getter?
If that does not work, please tell me, because then we should consider whether we should always apply the annotation based configurer or only if no custom one is defined. Or maybe we need to add support for priority based sorting there as well.

**Comment by wangzw** [comment]
For me, I prefer the following design.

1) Build in and user defined global interceptors are called before service specific interceptor.
2) All global interceptors are sorted based on order.
3) Service specific interceptors are called as the order they are declared in `GrpcService` annotation.

I cannot create a custom `GlobalServerInterceptorConfigurer `  since in `GrpcServerAutoConfiguration`  an `AnnotationGlobalServerInterceptorConfigurer` is created without condition.

```
@Configuration
@EnableConfigurationProperties
@ConditionalOnClass(Server.class)
@AutoConfigureAfter(GrpcCommonCodecAutoConfiguration.class)
public class GrpcServerAutoConfiguration {

......

    @Bean
    public AnnotationGlobalServerInterceptorConfigurer annotationGlobalServerInterceptorConfigurer() {
        return new AnnotationGlobalServerInterceptorConfigurer();
    }
```

**Comment by yidongnan** [comment]
I think that in the short term, we can provide a new interceptor after the global interceptor. Give the user enough time to do the upgrade migration, in the future we can change the default behavior of the current custom interceptor (after the global interceptor). 
Although we can also use custom interceptors before or after global ones, but there are almost no cases of using the before global interceptor.

**Comment by ncabanis** [comment]
We have the issue of ordering the global interceptors provided by your starter with our own global interceptors. The referenced PR looks good and seems to solve our problem.
