### ISSUE TITLE
Spring actuator doesn't work

### ISSUE THREAD

**Issue by chandresh-pancholi** [yidongnan/grpc-spring-boot-starter#251]
Hi,

How can I use spring actuator with this? Please suggest.

**Comment by ST-DDT** [comment]
Could you please be a little bit more specific?
Spring-Actuator is a very large framework.
What exactly do you wish to achieve?

Currently this library supports spring-actuator by
* exposing grpc-metrics of the `/actuator/metrics` endpoints
* exposing grpc-server details via the `/actuator/info` endpoint

All you have to do is add spring-actuator or more precisely `org.springframework.boot:spring-boot-starter-actuator` to your dependencies.

**Comment by chandresh-pancholi** [comment]
Apologies for not being clear. 
Our use case to manage log level at runtime. We are sending INFO Logs but when exceptions occur or alert comes when want to dynamically log DEBUG logs to ease our debug process. 
Actuator support dynamic log level change.

**Comment by ST-DDT** [comment]
And what exactly is your issue?
Are you unable to change the log level?
How is this related to grpc-spring-boot-starter?

**Comment by chandresh-pancholi** [comment]
Do you mind sharing the actuator endpoint for prometheus? 
I tried localhost:9090/actuator/metrics but it doesn't work.

**Comment by ST-DDT** [comment]
I'm not sure what your problem is.
Did you enable the metrics endpoint in your configuration?

````properties
management.endpoints.web.exposure.include=...,metrics
management.endpoint.metrics.enabled=true
````

Prometheus can be accessed if you have the required dependency and the below config:

````properties
management.endpoints.web.exposure.include=...,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
````

You can use `management.endpoints.web.exposure.include=*` to include all endpoints (not recommended)

**Comment by ST-DDT** [comment]
I hope this did help you. If not, feel free to comment with any questions you might have.

**Comment by towe75** [comment]
Hi,

sorry for coming back on this. I'm also wondering how to actually utilize the actuator with your starter. I included the actuator-starter, configured what i want and i see that intellij connects to it (presumably using jmx). 

Next, i expected to use the same port for both gRPC and actuator but can not manage to get it working. Maybe @chandresh-pancholi had the same problem? 

Also i tried your local-grpc-server project and it's same. Log complains about receiving a HTTP/1 request.

To make a long story short: do i have to add a second webserver for actuator rest endpoints or can it be combined in your netty server?

Maybe you can clearify and add it to your [upcoming documentation](https://st-ddt.github.io/grpc-spring-boot-starter/actuator).

**Comment by ST-DDT** [comment]
AFAIK there is no way to serve HTTP/Web actuator requests via netty (at least with spring).
So you will probably need a webserver (like tomcat) as well.

If you find find a way, please tell me.

**Comment by towe75** [comment]
Thx for quick response. 
Well, there should be some way because spring-boot-starter-webflux is also netty based and comes with actuator web endpoint support. If i simply reference spring-boot-start-webflux i end up with 2 netty servers on different ports, though. 
Maybe i can circumvent it by not using your shaded netty dependency?

**Comment by ST-DDT** [comment]
> Well, there should be some way because spring-boot-starter-webflux is also netty based and comes with actuator web endpoint support. If i simply reference spring-boot-start-webflux i end up with 2 netty servers on different ports, though.

For reactive apps this might be true, for legacy/normal servlet (?) based apps it's not.

> Maybe i can circumvent it by not using your shaded netty dependency?

Well, it's not exactly our's, but if you want to run the application with only one port then you will probably need `grpc-netty` instead of `grpc-netty-shaded` (especially if you use third party libs). As for the details on how this might work: I just don't know. Maybe the devs at grpc-java know.

---------------

PS: We (soft) depend on the shaded variant to avoid incompatibilities with netty versions defined in spring-boot's parent pom, as grpc-java seems to be strongly coupled to specific netty versions.

* https://st-ddt.github.io/grpc-spring-boot-starter/trouble-shooting#network-closed-for-unknown-reason
* https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty

-----------

Added a [todo](https://github.com/yidongnan/grpc-spring-boot-starter/issues/239#issuecomment-521286331) for the docs regarding the additional port+lib.

**Comment by towe75** [comment]
Ok, thank you for the hints. I will let you know if i find a solution.
