### ISSUE TITLE
StaticNameResolverProvider breaks resolving of GCP Pub Sub URLs

### ISSUE THREAD

**Issue by markusmueller** [yidongnan/grpc-spring-boot-starter#268]
net.devh.boot.grpc.client.nameresolver.StaticNameResolverProvider has the same priority as io.grpc.internal.DnsNameResolverProvider but is not able to handle the URLs for GCP Pub Sub but throwing an exception [1].

This prevents using this starter while also using pub sub.

Either StaticNameResolverProvider should have a lower priority than DnsNameResolverProvider or be able to handle these URLs. 

[1]: 
`Caused by: java.lang.NullPointerException: targetAuthority
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.devh.boot.grpc.client.nameresolver.StaticNameResolverProvider.of(StaticNameResolverProvider.java:76)
	at net.devh.boot.grpc.client.nameresolver.StaticNameResolverProvider.newNameResolver(StaticNameResolverProvider.java:63)`

**Comment by ST-DDT** [comment]
The next version (going to be released soon) reduces the priority of the `StaticNameResolverProvider` to below `dns`. However, it should be possible to avoid this issue altogether if you specify the address in a way that tells the server what it actually represents (and thus prevents the static resolver to touch it).

How do you specify the target address? (I haven't seen any GCP Pub Sub urls yet, so I would be grateful for an example)

It should looks somewhat like this:

````properties
grpc.client.__name__.address=dns:///example.com
````

**Comment by markusmueller** [comment]
Good to hear that the priority will be reduced, so we can get rid of our workaround! :-)

The default URLs to the GCP pub sub api are defined in the pub sub java library, for example in: https://github.com/googleapis/google-cloud-java/blob/0786a243e6b24c0b465fb4ff7a74517147aed0f1/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java#L255

**Comment by ST-DDT** [comment]
Is the actual problem the mere presence of the `StaticNameResolverProvider` respectively that grpc-java finds and uses it, even if the rest doesn't use grpc-spring-boot-starter at all?

In that case you are just one step away from struggling again. E.g. if someone adds another library that contains a `NameResolverProvider` then your connection will fail again. In fact, this library contains a service discovery name resolver that has a (currently only theoretically) higher priority than the dns resolver. Unless you tell it to use dns you will head straight into trouble anyway.

-----------------------

Do you use grpc-spring-boot-starter to inject the `SubscriberStub`(?) or do you create it yourself?
If you use grpc-spring-boot-starter for injection: How do you configure the channel target? AFAIK spring-boot does not support static method invocations to derive the actual value.

**Comment by markusmueller** [comment]
> Is the actual problem the mere presence of the `StaticNameResolverProvider` respectively that grpc-java finds and uses it, even if the rest doesn't use grpc-spring-boot-starter at all?

Yes, the StaticNameResolverProvider is loaded through the java service loader mechanism as its implementing the NameResolver interface. No Spring involved here. 

> In that case you are just one step away from struggling again. E.g. if someone adds another library that contains a NameResolverProvider then your connection will fail again. In fact, this library contains a service discovery name resolver that has a (currently only theoretically) higher priority than the dns resolver. Unless you tell it to use dns you will head straight into trouble anyway.

If other potential providers will not be able to handle the default URLs, yes. I think one way to prevent this would be not to throw an exception if the URL can not be handled but set the availability of the resolver to false, as mentioned in: https://github.com/grpc/grpc-java/blob/4faad27078ddc63825fbe0f04ba3e4a0ec6dff16/api/src/main/java/io/grpc/NameResolverProvider.java#L23

> Do you use grpc-spring-boot-starter to inject the SubscriberStub(?) or do you create it yourself?
If you use grpc-spring-boot-starter for injection: How do you configure the channel target? AFAIK spring-boot does not support static method invocations to derive the actual value.

No, grpc-spring-boot-starter is not used to create any pub sub related stubs.

**Comment by ST-DDT** [comment]
> > Is the actual problem the mere presence of the `StaticNameResolverProvider` respectively that grpc-java finds and uses it, even if the rest doesn't use grpc-spring-boot-starter at all?
> 
> Yes, the StaticNameResolverProvider is loaded through the java service loader mechanism as its implementing the NameResolverProvider interface. No Spring involved here.

As you can see [here](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/StaticNameResolverProvider.java#L63) and [here](https://github.com/grpc/grpc-java/blob/63f636b4b61ff0fbf28f09666bc3bfbea6e6af99/core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java#L47), the name resolvers will only budge, if they are explicitly addressed. If after the first run nobody took action (because no scheme is present) then grpc-java will try a second run with and use the [ManagedChannelImpl](https://github.com/grpc/grpc-java/blob/63f636b4b61ff0fbf28f09666bc3bfbea6e6af99/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L685) will use the default scheme, which is the scheme from the NameResolverProvider with the highest priority or a configured one.

In the next release of this library this order will be:

* `discovery` (if a `DiscoverClient` bean is available)
* `dns`
* `static`

Maybe we should open an issue in that library, that they should change their default logic to explicitly use the `dns:` scheme prefix.

> > In that case you are just one step away from struggling again. E.g. if someone adds another library that contains a NameResolverProvider then your connection will fail again. In fact, this library contains a service discovery name resolver that has a (currently only theoretically) higher priority than the dns resolver. Unless you tell it to use dns you will head straight into trouble anyway.
> 
> If other potential providers will not be able to handle the default URLs, yes. I think one way to prevent this would be not to throw an exception if the URL can not be handled but set the availability of the resolver to false, as mentioned in: https://github.com/grpc/grpc-java/blob/4faad27078ddc63825fbe0f04ba3e4a0ec6dff16/api/src/main/java/io/grpc/NameResolverProvider.java#L23

As for setting the availability to false: I can only do this globally, I cannot do this on a per URL level.
As for not throwing an exception: This is the funny part, as for the API contract I'm not allowed to throw an exception, but even the [dns resolver](https://github.com/grpc/grpc-java/blob/63f636b4b61ff0fbf28f09666bc3bfbea6e6af99/core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java#L49) throws one.
Maybe throwing an NPE isn't the best choice here, but I will probably just throw an IAE instead.
The main issue here is that that library does not define a scheme and thus grpc-java uses the default scheme.
If I really wouldn't throw an Exception, then this still wouldn't fix the issue because the DNS resolver won't get invoked afterwards (There is nothing left after the fallback).

Luckily there are two (one) possible workarounds:

1) Configure the default scheme in grpc-spring-boot-starter (which does not help you in this case)
   ````java
   @Bean
   public NameResolver.Factory grpcNameResolverFactory(final GrpcChannelsProperties channelProperties) {
       return new ConfigMappedNameResolverFactory(channelProperties,
               StaticNameResolverProvider.STATIC_DEFAULT_URI_MAPPER) {
               public String getDefaultScheme() { return "your default here"; }
       };
   }
   ````

2) Configure the pub sub [endpoint address](https://github.com/googleapis/google-cloud-java/blob/0786a243e6b24c0b465fb4ff7a74517147aed0f1/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java#L603) with the dns prefix: `builder.setEndpoint("dns:///" + getDefaultEndpoint());`



> > Do you use grpc-spring-boot-starter to inject the SubscriberStub(?) or do you create it yourself?
> > If you use grpc-spring-boot-starter for injection: How do you configure the channel target? AFAIK spring-boot does not support static method invocations to derive the actual value.
> 
> No, grpc-spring-boot-starter is not used to create any pub sub related stubs.

Do you use any grpc-spring-boot-starter client features at all? If not you could use only the server part of this library.

**Comment by markusmueller** [comment]
> Do you use any grpc-spring-boot-starter client features at all? If not you could use only the server part of this library.

In this case we are using client starter features, but we do not need any of the features provided by the StaticNameResolver. The quick workaround for now is to provide a DnsNameResolver with max priority. 

SubscriberSettings for Pub Sub are coming from https://github.com/spring-cloud/spring-cloud-gcp/blob/72d746486fedd19b16ead3cdbbcfb48c3e90c3a9/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/support/DefaultSubscriberFactory.java#L242. It would also be possible to provide a custom factory which is adding the schema to the URL.

**Comment by ST-DDT** [comment]
With the v2.5.0 the main issue should be fixed. I will improve the configurability of the default scheme in #237. The rest is up to GCP to fix/improve.
Does this solve your issues?

**Comment by markusmueller** [comment]
Yes, the main issue is fixed with the new release, thanks for looking into it! Feel free to close this ticket.

**Comment by ST-DDT** [comment]
https://github.com/spring-cloud/spring-cloud-gcp/pull/2085
