### ISSUE TITLE
Any way to not reuse grpc connection?

### ISSUE THREAD

**Issue by wangzw** [yidongnan/grpc-spring-boot-starter#272]
Use case: 

Two or more grpc servers work independently for HA. And a load balance provides a unified endpoint for all clients. Load balance works under round robin mode and do not keep session.

The client try to connect the endpoint in a loop. The server will reject duplicated connection request from the same client. Ideally, the client will eventually connect to all servers. 

But if `GrpcChannelFactory` always return a reused grpc channel, the client will constantly send request to the same server.

So is there any way to force the `GrpcChannelFactory` to return a new channel?

**Comment by wangzw** [comment]
I managed to create a new channel by invoking `AbstractChannelFactory::newManagedChannel` and  shutdown channel manually.

**Comment by ST-DDT** [comment]
Am I correct with my assumption that you have to create a new connection for every grpc call you are making? In that case your workaround does not fix your actual problem. Because as soon as you are sending a second request via the injected stubs you will encounter the same issue again!

From my perspective there are 2 possible workarounds and 2 possible solutions:

* Re-Create the channel and stubs for every call.
* Set the max connection age to a very low value (~10ms?) and configure a max connection grace period long enough to finish the call (https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#maxConnectionAgeGrace-long-java.util.concurrent.TimeUnit-) there might be something similar for clients, but maybe configuring the server like this is enough.

* Change your server setup to either expose the target servers and use client side load balancing
* or make your load balancer transparent to the clients

Is there a special reason in forcing your clients to reconnect on every call? Those reconnects aren't cheap either.

**Comment by wangzw** [comment]
Thanks for your details answer. 

Actually I only need to create a new connection for the first call, and then reuse the connection for the following calls if the server accept the request of the first call. And my comments above works well and solve my issue.

More details about my use case. Client do not know how many of server is behind the load balance and it will constantly try to make new connection to server with its unique id. Once the connection is established, the client reuse the connection and start working with the server. And at the same time, the client will try to connect another server behind the same load balance. A client can work with many servers. If server has established a connection with the client, it will reject the following connect request from the same client. So eventually all clients will connect all servers if the load balance works under round robin mode.
