### ISSUE TITLE
客户端启动报错

### ISSUE THREAD

**Issue by wangyingwei001** [yidongnan/grpc-spring-boot-starter#309]
Parameter 1 of method grpcInfoContributor in net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration required a bean of type 'io.grpc.BindableService' that could not be found.

版本2.4.0

**Comment by ST-DDT** [comment]
You are probably referring to this bean:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/v2.4.0.RELEASE/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerMetricAutoConfiguration.java#L77

First of all consider upgrading to the latest version since we have fixed some issues in the meantime.

As for your specific issue:
Do you have a bean that is annotated with `@GrpcService` and extends one of grpc's `...ImplBase` classes and thus extends `BindableService`?

**Comment by ST-DDT** [comment]
Closing due to missing feedback.
