### ISSUE TITLE
Request connection on startup

### ISSUE THREAD

**Issue by genuss** [yidongnan/grpc-spring-boot-starter#376]
**The problem**

I'd like to get immediate feedback on configuration errors via checking a connection to GRPC server on startup.

**The solution**

I propose to modify `net.devh.boot.grpc.client.channelfactory.AbstractChannelFactory#watchConnectivityState()` by making a param passed to `requestConnection` configurable. Configuration param may be set in `GrpcChannelsProperties` preserving default value.

**Alternatives considered**

Another solution could be waiting for the first actual request and later seeing result via `HealthIndicator` but this has drawback for low-load services or forces GRPS-server's developers to implement some kind of health endpoint on their side for the first request.

Unfortunately I can't get a `ManagedChannel` in "user-space" code because it's hidden deep in `InterceptorChannel`

**Additional context**

The best way would be failing a context to start but I couldn't find proper way in GRPC to check for connection in a synchronous way.

I could make a PR, looks simple enough for me.

**Comment by ST-DDT** [comment]
Sounds like a useful feature to me.
IMO we should go for a new property in the config like `grpc.client.<name>.immediateConnect` (feel free to propose a better name).

Requirements:
- The property needs to be false by default
- The description of the property should state, that setting this to true, will only check the connection when the factory is created first and bean creation will fail to be created (thus may be failing the application startup). 
- The startup performance implications should also be stated (potential delay due to waiting for timeout)
- The behavior of the feature should be predictable (grpc's getConnectivityState method needs to be blocking)

> I could make a PR, looks simple enough for me.

We welcome new contributors and I look forward to your contribution. 👍
