### ISSUE TITLE
StaticSecurityHeaderCallCredentials could be public

### ISSUE THREAD

**Issue by asarkar** [yidongnan/grpc-spring-boot-starter#385]
**The problem**

`CallCredentialsHelper.StaticSecurityHeaderCallCredentials` is a `private` class.

**The solution**

Pull it out of `CallCredentialsHelper`, make it `public`, and rename to `StaticHeaderCallCredentials`.

**Alternatives considered**

I'm having to reimplement what's already in  `StaticSecurityHeaderCallCredentials`.

**Additional context**

Adding static headers (not only security related) to a client call is a very common need.

**Comment by ST-DDT** [comment]
> **The solution**
> 
> Pull it out of `CallCredentialsHelper`, make it `public`, and rename to `StaticHeaderCallCredentials`.
> 
> **Alternatives considered**
> 
> I'm having to reimplement what's already in `StaticSecurityHeaderCallCredentials`.

I'm slightly hesitant in making it public API, as the class in itself is almost trivial to implement yourself and I don't wish it to be used for something outside of the auth stuff. Especially regarding the expectations other developers might have regarding the behavior of that class. However, I could imagine adding another method like : 

````java
public static CallCredentials authorizationHeader(String authorization) {
    Metadata extraHeaders = new Metadata();
    extraHeaders.put(AUTHORIZATION_HEADER, authorization);
    return new StaticSecurityHeaderCallCredentials(extraHeaders);
}
````

Maybe even something like this:

````java
public static CallCredentials authorizationHeaders(Metadata authorizationHeaders) {
    return new StaticSecurityHeaderCallCredentials(authorizationHeaders);
}
````

Would any of these solve your issue? 

>Adding static headers (not only security related) to a client call is a very common need.

Instead of using `CallCredentials` for that how about using [`MetadataUtils.attachHeaders(stub, extraHeaders)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/MetadataUtils.html#attachHeaders-T-io.grpc.Metadata-)?

If you wish to apply them to all your stubs, you can use the global interceptor registry or a `StubTransformer` for that.

**Comment by asarkar** [comment]
`CallCredentials authorizationHeaders(Metadata authorizationHeaders)` would do the job. I'll look into the global `StubTransformer` that you suggested, thank you.
