### ISSUE TITLE
Add ServiceInstance.metadata to EquivalentAddressGroup.attributes

### ISSUE THREAD

**Issue by funcfoo** [yidongnan/grpc-spring-boot-starter#429]
**The problem**

- We wanted to use EquivalentAddressGroup.attributes in custom LoadBalancer. but I got these attributes is empty.

**The solution**

```
            for (final ServiceInstance instance : newInstanceList) {
                final int port = getGRPCPort(instance);
                log.debug("Found gRPC server {}:{} for {}", instance.getHost(), port, name);
                Attributes.Builder attributesBuilder = Attributes.newBuilder();
                for (Map.Entry<String, String> entry : instance.getMetadata().entrySet()) {
                    attributesBuilder.set(Attributes.Key.create(entry.getKey()), entry.getValue());
                }
                targets.add(new EquivalentAddressGroup(
                        new InetSocketAddress(instance.getHost(), port), attributesBuilder.build()));
            }
```

**Additional context**

- We wanted to replace DiscoveryClientResolverFactory, but this implementation is not an interface.

**Comment by ST-DDT** [comment]
Is there any documentation on which attributes "should" exist or their semantics?
Or is that entirely up to the lb implementation?

**Comment by funcfoo** [comment]
Thanks for your reply.

This feature request just up to the load-balancer.

If it's not a good design. 

** alternatives **
Can we change DiscoveryClientResolverFactory config to NameResolverProvider?
```
    @ConditionalOnMissingBean(name='grpcDiscoveryClientResolverFactory')
    @Lazy
    @Bean
    NameResolverProvider grpcDiscoveryClientResolverFactory(final DiscoveryClient client) {
        return new DiscoveryClientResolverFactory(client);
    }
```

** alternatives **
Can we change DiscoveryClientResolverFactory to AbstractDiscoveryClientResolverFactory?
```
class AbstractDiscoveryClientResolverFactory extends NameResolverProvider {
}
class DiscoveryClientResolverFactory extends AbstractDiscoveryClientResolverFactory {
}
class GrpcDiscoveryClientAutoConfiguration {
    @ConditionalOnMissingBean
    @Lazy
    @Bean
    AbstractDiscoveryClientResolverFactory grpcDiscoveryClientResolverFactory(final DiscoveryClient client) {
        return new DiscoveryClientResolverFactory(client);
    }
}
```

**Comment by ST-DDT** [comment]
I'll try to read more about the parameters and how they are supposed to be used myself then.

As for your alternatives:
AFAICT you wish to prevent the discovery bean from being created. Why?
If you define a `NameResolverProvider` with a higher priority, it will be used instead of the included one.
If you wish to avoid unnecessary bean from being created you can also use the spring.autoconfigure.exclude property to skip that autoconfiguration class completely.

However, I might end up adding the `DiscoveryClientResolverFactory` to the public API in the next release to allow overwriting/configuring it.
(Depends a little bit on the result of my research and might take a while)

**Comment by funcfoo** [comment]
Thanks

**Comment by ST-DDT** [comment]
It is impossible to map the metadata to attributes, because the attributes rely on hard-coded keys to be useful.
But I made the existing implementation more flexible by allowing it to be overwritten in the most important parts.
See also #600
