### ISSUE TITLE
Enabling SSL in GRPC setup on Springboot

### ISSUE THREAD

**Issue by binaradarsha** [yidongnan/grpc-spring-boot-starter#49]
I was struggling in enabling SSL in Grpc which is setup on Springboot. Finally I found and put following application properties.

`gpc.server.security.enabled = true`
`gpc.server.security.certificate-chain-path: /home/user/SpringBootGrpc2/src/main/resources/Certificate.crt`
`gpc.server.security.certificate-path: /home/user/SpringBootGrpc2/src/main/resources/Private-key.key`

I gave server certificate path to certificate-chain-path, and server private key file to certificate-path. Now seems SSL works fine, but I have a doubt on giving private key file to certificate-path.

Is this correct or if not what are the correct property names?

**Comment by uweschaefer** [comment]
just a note: there is ":" instead of "=" on the 2nd and third property. Just in case you missed it.

**Comment by binaradarsha** [comment]
Thanks for noting this, I will check.

**Comment by ST-DDT** [comment]
I checked the code and `certificatePath` actually refers to the `privateKeyPath`.

AFAICT a certificate is just a public key with some metadata that is send to the client, so that he can encrypt the bytes with it. The server then needs the private key to decrypt those bytes. The certificate chain is used to verify whether the server is trustworthy by checking if at least one certificate in that chain is trusted by the client.

------------------------------------

I'm not sure whether you can write Spring properties using `kebab-case` the properties are spelled like this:
* `grpc.server.security.enabled`
* `grpc.server.security.certificateChainPath`
* `grpc.server.security.certificatePath`

and can be assigned like this in properties file:

````properties
key=value
````

Other combinations/cases might work as well, but I haven't checked which of them actually do.
In YAML other ways might be possible.

You can read more about that here: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by ST-DDT** [comment]
I assume the underlying issue is fixed with the property being renamed and the additional docs.

I guess this issues can be closed now.
