### ISSUE TITLE
Add status tag to call counter metric

### ISSUE THREAD

**Issue by asarkar** [yidongnan/grpc-spring-boot-starter#526]
**The problem**

The server and client call counters don’t have a status tag. Thus, it is impossible to do something meaningful with it, like creating an alert if a certain number of calls have failed within the last x minutes.

**The solution**

Add gRPC call status as a tag to the counters, similar to how it’s added to the latencies.

**Alternatives considered**

Create my own metrics implementation.

**Comment by ST-DDT** [comment]
Which metric are you referring to exactly?

AFACIT `grpc.server.processing.duration` which also has a `COUNT` has a `statusCode` tag.

![grafik](https://user-images.githubusercontent.com/1579362/115579699-b3480d00-a2c6-11eb-915f-2e86ee8095aa.png)

**Comment by ST-DDT** [comment]
Or are you referring to `grpc.server.responses.sent`?
These don't contain a status, because the status is not known at the time they are sent.
Also errors don't increment this counter at all.

If I were to wait for the call to complete/the status to be know, then I would loose the information that a long running task still receives requests/sends responses and how evenly they are sent.

**Comment by asarkar** [comment]
I was referring to `grpc.server.responses.sent`. I realized that `grpc.server.processing.duration` is a timer, which has an inherent counter; I'll see if I can use that to find out how many calls failed.
