### ISSUE TITLE
GRPC.Client. ADRESS cannot be injected through the System Environment

### ISSUE THREAD

**Issue by gqhao0521** [yidongnan/grpc-spring-boot-starter#558]
![image](https://user-images.githubusercontent.com/41989618/122855337-ad62bc80-d347-11eb-8376-a2ab4458ee78.png)

**Comment by ST-DDT** [comment]
The property is called 
`grpc.client.<name>.address`
 instead of
`grpc.client.address`.

Does that solve the issue for you?

**Comment by gqhao0521** [comment]
> The property is called
> `grpc.client.<name>.address`
> instead of
> `grpc.client.address`.
> 
> Does that solve the issue for you?

**Comment by gqhao0521** [comment]
> The property is called
> `grpc.client.<name>.address`
> instead of
> `grpc.client.address`.
> 
> Does that solve the issue for you?

no,it can't solve the problem.
My configuration is exactly grpc.client.<name>.address, I mean this property cannot be injected through the environment variable (GRPC_NRGOTIATION_TYPE)
Here is my configuration file,
grpc:
  client:
    region-mapping:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: ${GRPC_NRGOTIATION_TYPE:TLS}
      address: ${GRPC_CLIENT_ADDRESS:static://xxxx:80}
      ...

**Comment by ST-DDT** [comment]
The exception message in the title states, that the `grpc.client.address` does not exist.
I have checked it using an example application with this config:

````properties
grpc.client.test.address=${GRPC_ADDRESS:localhost:9090}
````

Configuring it like this worked for me in the following scenarios:

- No value provided for that property
- Value provided via -D VM arguments
- Value provided via ENV

AFAICT the issue here is that you have named the properties to be partially matching existing configurations.
Spring will automatically convert ENV variables to existing properties if matching. Unfortunately the `GRPC_CLIENT` prefix you have chosen is also used by `grpc.client` and thus spring tries to convert it as that.

Choose a different property name and everything will work as expected.
