### ISSUE TITLE
能否支持nacos或者其他配置中心组件实时动态修改配置

### ISSUE THREAD

**Issue by FanForerver** [yidongnan/grpc-spring-boot-starter#597]
**The context**

What do you wish to achieve?

**The question**

What's the problem? What's not working? What's missing and why do you need it?

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

**The application's environment**

Which versions do you use?
* Spring (boot):
* grpc-java:
* grpc-spring-boot-starter:
* java: version + architecture (64bit?)
* Other relevant libraries...

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by ST-DDT** [comment]
[English Translation](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/597?_x_tr_sl=zh-CN&_x_tr_tl=en)

> Can it support nacos or other configuration center components to dynamically modify the configuration in real time?

---------------

No, this is currently not supported other than the native spring support. I'm not sure what exactly needs to be done to support that. Do you have a guide for that?

**Comment by FanForerver** [comment]
我们没有使用注册中心，对于客户端服务端地址是直接配置在nacos的，我们需要面对服务端地址变化的情况

**Comment by ST-DDT** [comment]
If I understand you correctly then you wish to change the address the client uses to connect to an external server.

This is already supported using the `discovery` protocol (`DiscoveryClient`).

See also:
https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#choosing-the-target

This documentation is slightly outdated but might not require additional translation.
https://yidongnan.github.io/grpc-spring-boot-starter/zh-CN/client/configuration.html

**Comment by FanForerver** [comment]
感谢你的帮助，我之前就注意到这个了，不过这个似乎依赖eureka等注册中心组件，我们不想使用这些组件，我们未来期望使用k8s来实现，目前只希望解决服务端地址变化客户端能感知并且修改连接。

**Comment by ST-DDT** [comment]
Nacos has a registry as well.
If both of your applications runs inside kubernetes then you could use a K8s-Service to point to the right pod/address and use the `dns` resolver with `dns:///myservice`

**Comment by ST-DDT** [comment]
You could also write a custom Nameresolver that is connected to nacos directly or updates itself from the config if triggered by "refresh" events.

**Comment by FanForerver** [comment]
感谢，我是grpc的新手，我有两个疑问，1.什么时候DnsNameResolver 会调用refresh方法，他是否能直接解决我的问题
2.如果我尝试自己写一个custom Nameresolver ，官方Nameresolver 的实质更新的方法是哪个呢，是否像这样            listener.onResult(ResolutionResult.newBuilder().setAddresses(newAddresses).build());

**Comment by ST-DDT** [comment]
1) I'm not exactly sure when any `NameResolver` will refresh itself . Usually if a new connection is made, either due to not having one or losing one. I don't know if there are "random" periodic updates. The developers over at grpc-java or stackoverflow might know more details.

2) If you wish to implement it yourself, then you use the [`DiscoveryNameResolver`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java#L121) as a reference.

You can also try to combine them both. If you only implement a custom `DnsNameResolverFactory` that keeps a reference to the created `DnsNameResolver`, then you could use the factory to forward the refresh command to the name resolvers.
The [`DiscoveryClientResolverFactory`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientResolverFactory.java#L109) does that with the `DiscoveryClientNameResolver`s. That way you don't have to implement the more complex `NameResolver`s but only the lightweight `NameResolverFactory`.

**Comment by FanForerver** [comment]
thanks,I will try it

**Comment by liuxuzxx** [comment]
> Nacos has a registry as well. If both of your applications runs inside kubernetes then you could use a K8s-Service to point to the right pod/address and use the `dns` resolver with `dns:///myservice`

After the Pod is expanded, how does the grpc client perceive it?
