### ISSUE TITLE
grpc metadata support

### ISSUE THREAD

**Issue by mizanRahman** [yidongnan/grpc-spring-boot-starter#61]
does this library support metadata on rpc requests? 
grpc-go has metadata support:
https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md

**Comment by ST-DDT** [comment]
I assume this question is probably better suited in the grpc-java repo, because this library does not provide or change the behavior of the grpc-stuff.

AFAICT you cannot access the meta data in the actual service, due to the grpc-library no providing a parameter for that, but I'm not sure whether it is supposed to be like that in the first place.

It is possible to access and modify the metadata in interceptors though.

Here the signature of the ServerInterceptor:
`ServerCall.Listener<RequestT> startCall(ServerCall<RequestT, ResponseT>, Metadata);`

**Comment by ST-DDT** [comment]
This question/request cannot be properly answered by this library. If you have something that this library could do to help you with your request please comment below.
