### ISSUE TITLE
Is grpc-spring-boot-starter interested in sponsoring?

### ISSUE THREAD

**Issue by uweschaefer** [yidongnan/grpc-spring-boot-starter#941]
**The context**

I would like to help this project, as we use it in critical infrastructure.
(also we'd love to see SB3 compatibility soon :wink: )

**The question**

My employer (http://prisma-capacity.eu/) has a budget for sponsoring OSS Projects, and i was wondering, if it made sense to suggest to sponsor [grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter).

Sponsoring through github or opencollective or similar platforms is thinkable for us.

**Comment by yidongnan** [comment]
Thank you very much for your offer to support the project. I really appreciate your willingness to contribute. However, I must clarify that due to my current location, I'm unable to utilize GitHub Sponsors.

The good news is that the most recent release partially supports Spring Boot 3.x, and the master branch has fully transitioned to Spring Boot 3.x. This should align well with your needs.

Thank you once again.
